/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookmyshow;

import javax.swing.JFrame;

/**
 *
 * @author Meghana Patil
 */
public class Congrats extends javax.swing.JFrame {

   // private Object java;
   // private Object java;

    /**
     * Creates new form Congrats
     */
    public Congrats() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        //gst_label.setText(PaymentProcess.gst_str+" Rs.");
        final_amt.setText(PaymentProcess.total_str+" Rs.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        payment_confirm_panel = new javax.swing.JPanel();
        final_amt = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        payment_confirm_panel.setBackground(new java.awt.Color(255, 255, 255));
        payment_confirm_panel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 20, true));
        payment_confirm_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        final_amt.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        payment_confirm_panel.add(final_amt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 260, 80));

        jPanel3.setBackground(new java.awt.Color(92, 188, 92));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Check Mark.png"))); // NOI18N
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setText("Congratulations!!");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 330, 79));

        payment_confirm_panel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 480, 230));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Your Payment has Successfully received");
        payment_confirm_panel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 331, 41));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Paytm.png"))); // NOI18N
        payment_confirm_panel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, 110, 50));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Bhim.png"))); // NOI18N
        payment_confirm_panel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, 60, 50));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Google Pay India.png"))); // NOI18N
        payment_confirm_panel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, 50, 50));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Phone Pe.png"))); // NOI18N
        payment_confirm_panel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, 50, 50));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MasterCard.png"))); // NOI18N
        payment_confirm_panel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 480, 50, 50));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("OK");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        payment_confirm_panel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 130, 50));

        getContentPane().add(payment_confirm_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 140, 520, 550));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/film image.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1920, 1080));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Bookmyshowframe().show();
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Congrats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Congrats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Congrats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Congrats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Congrats().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel final_amt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel payment_confirm_panel;
    // End of variables declaration//GEN-END:variables
}
